# Copyright (c) 2023 - 2024 Schweitzer Engineering Laboratories, Inc.
# SEL Confidential

publishBranch: "main"

paths:
  workspaceRoot: "/workspaces/butler"
  resultsFilePath: "./butler_results.json"
  criticalPaths:
    - .devcontainer/devcontainer.json
    - .butler.base.yaml
    - .butler.ignore.yaml
    - code

tasks:
  runAll: false
  lint: true
  test: true
  build: false
  publish: false

languages:
  - name: "golang"
    filePatterns: 
      - ".go"
    builtinStdLibsMethod: true
    builtinWorkspaceDepMethod: true
    builtinExternalDepMethod: true
    dependencyCommands:
      external: "go run ./code/butler/test_data/test_repo/user_commands/go_external_deps_method.go"
    taskCommands: 
      lint: "/go/bin/golangci-lint run --timeout 5m --allow-parallel-runners --concurrency=1 ."
      test: "go run /workspaces/butler/user_commands/go_testing_command/go_testing_command.go"
      setUp:
          - "echo go test"