# Copyright (c) 2023 - 2024 Schweitzer Engineering Laboratories, Inc.
# SEL Confidential

allowed-paths:
  - code
  - test_repo

blocked-paths:
  - node_modules
  - coverage
  - specs
  - .devcontainer