# Copyright (c) 2023 - 2024 Schweitzer Engineering Laboratories, Inc.
# SEL Confidential

publishBranch: "main"

paths:
  allowedPaths:
    - test_repo
  ignorePaths:
    - blocked_dir
  workspaceRoot: "./test_data/test_configs/bad_ignore_configs/ignore_dir"

languages:
  - name: "golang"
    filePatterns: 
      - ".go"
    dependencyCommands:
      external: "go run ./user_commands/go_external_deps_method.go"
    taskCommands: 
      lint: "echo go lint command"
      test: "echo go test command"
      build: "echo go build command"
      publish: "echo go publish command"
      setUp:
          - "echo go test"