# Copyright (c) 2023 - 2024 Schweitzer Engineering Laboratories, Inc.
# SEL Confidential

publish-branch: "main"

paths:
  allowed-paths:
    - test_repo
  workspace-root: "./test_data/test_configs/bad_ignore_configs"

languages:
  - name: "golang"
    filePatterns: 
      - ".go"
    builtinStdLibsMethod: true
    builtinInternalDepMethod: true
    builtinExternalDepMethod: true
    dependencyCommands:
      externalDepCommand: "go run ./user_commands/go_external_deps_method.go"
    taskCommands: 
      lintCommand: "echo go lint command"
      testCommand: "echo go test command"
      buildCommand: "echo go build command"
      publishCommand: "echo go publish command"
      setUpCommands:
          - "echo go test"