# Copyright (c) 2023 - 2024 Schweitzer Engineering Laboratories, Inc.
# SEL Confidential

# files in this directory are used for testing when Butler lacks read permissions for config files.

paths:
  workspace-root: "./test_data/bad_configs/no_read_permissions"