# Copyright (c) 2023 - 2024 Schweitzer Engineering Laboratories, Inc.
# SEL Confidential

paths:
  workspace-root: "./test_data/bad_configs"

git:
  git-repository: true

languages:
  - Name: "golang"
    FileExtension: ".go"
    Commands: 
      LintCommand: "echo go lint command"
      TestCommand: "echo go test command"
      BuildCommand: "echo go build command"
      PublishCommand: "echo go publish command"
      ExternalDepCommand: "go run /workspaces/butler/user_commands/go_external_deps_method.go"
      SetUpCommands:
          - "echo go test"