# Copyright (c) 2023 - 2024 Schweitzer Engineering Laboratories, Inc.
# SEL Confidential

paths:
  workspace-root: "../.."
  allowed-paths:
    - test_repo

  blocked-paths:
    - ci/
    - specs
    - .devcontainer

tasks:
  should-run-all: false
  should-lint: true
  should-test: true
  should-build: false
  should-publish: false

languages:
  - name: "golang"
    filePatterns: 
      - "package.json"
    builtinStdLibsMethod: true
    builtinInternalDepMethod: true
    builtinExternalDepMethod: true

    taskCommands: 
      lintCommand: "echo go lint command"
      testCommand: "echo go test command"
      buildCommand: "echo go build command"
      publishCommand: "echo go publish command"
      setUpCommands:
          - "echo go test"