# Copyright (c) 2023 - 2024 Schweitzer Engineering Laboratories, Inc.
# SEL Confidential

publish-branch: "main"

paths:
  workspace-root: "../.."
  allowed-paths:
    - test_repo

  blocked-paths:
    - ci/
    - specs
    - .devcontainer
    - bad_configs

tasks:
  should-run-all: false
  should-lint: true
  should-test: true
  should-build: false
  should-publish: false

languages:
  - name: "golang"
    filePatterns: 
      - ".go"
    builtinStdLibsMethod: true
    builtinInternalDepMethod: true
    builtinExternalDepMethod: true
    dependencyCommands:
      externalDepCommand: "go run ./user_commands/go_external_deps_method.go"
    taskCommands: 
      lintCommand: "echo go lint command"
      testCommand: "echo go test command"
      buildCommand: "echo go build command"
      publishCommand: "echo go publish command"
      setUpCommands:
          - "fail command"