# Copyright (c) 2023 - 2024 Schweitzer Engineering Laboratories, Inc.
# SEL Confidential

publishBranch: "butler_unit_test_main"

paths:
  workspaceRoot: "./test_data"
  allowedPaths:
    - test_repo

  ignorePaths:
    - blocked_dir

tasks:
  runAll: false
  lint: true
  test: true
  build: false
  publish: false

languages:
  - name: "golang"
    filePatterns: 
      - ".go"
    dependencyOptions:
      dependencyAnalysis: true
      excludeStdLibs: true
      externalDependencies: true
    dependencyCommands:
      external: "go run ./test_repo/user_commands/go_external_deps_method.go"
    taskCommands: 
      lint: "echo go lint command"
      test: "echo go test command"
      build: "echo go build command"
      setUp:
          - "echo go test"