# Copyright (c) 2023 - 2024 Schweitzer Engineering Laboratories, Inc.
# SEL Confidential

paths:
  allowed-paths:
    - test_repo
  workspace-root: "./test_data/bad_configs/ignore_dir"

git:
  git-repository: true

languages:
  - name: "golang"
    fileExtension: ".go"
    dependencyCommands:
      externalDepCommand: "go run /workspaces/butler/user_commands/go_external_deps_method.go"
    taskCommands: 
      lintCommand: "echo go lint command"
      testCommand: "echo go test command"
      buildCommand: "echo go build command"
      publishCommand: "echo go publish command"
      setUpCommands:
          - "echo go test"