# Copyright (c) 2023 - 2024 Schweitzer Engineering Laboratories, Inc.
# SEL Confidential

paths:
  workspace-root: "/workspaces/butler"
  allowed-paths:
    - test_repo

  blocked-paths:
    - ci/
    - specs
    - .devcontainer
    - bad_configs

git:
  publish-branch: "main"
  git-repository: true

tasks:
  should-run-all: false
  should-lint: true
  should-test: true
  should-build: false
  should-publish: false

languages:
  - name: "invalid"
    dependencyCommands:
      externalDepCommand: "echo collect deps"
    taskCommands: 
      lintCommand: "echo lint command"
      testCommand: "echo test command"
      buildCommand: "echo build command"
      publishCommand: "echo publish command"
      setUpCommands:
          - "echo test"