# Copyright (c) 2023 - 2024 Schweitzer Engineering Laboratories, Inc.
# SEL Confidential

allowed-paths:
  - test_repo

blocked-paths:
  - ci/
  - specs
  - .devcontainer


workspace-root: "/workspaces/butler"

publish-branch: "main"

git-repository: false

should-run-all: false

should-lint: true
should-test: true
should-build: false
should-publish: false
should-package: false