# Copyright (c) 2023 - 2024 Schweitzer Engineering Laboratories, Inc.
# SEL Confidential

paths:
  workspace-root: "../.."
  allowed-paths:
    - test_repo

  blocked-paths:
    - ci/
    - specs
    - .devcontainer
    - bad_configs

git:
  publish-branch: "main"
  git-repository: true

tasks:
  should-run-all: false
  should-lint: true
  should-test: true
  should-build: false
  should-publish: false