# Copyright (c) 2023 - 2024 Schweitzer Engineering Laboratories, Inc.
# SEL Confidential

paths:
  workspace-root: "../.."
  allowed-paths:
    - test_repo

  blocked-paths:
    - ci/
    - specs
    - .devcontainer

git:
  publish-branch: "main"
  git-repository: false

tasks:
  should-run-all: false
  should-lint: true
  should-test: true
  should-build: false
  should-publish: false

languages:
  - Name: "golang"
    FileExtension: ".go"
    DependencyCommands:
      ExternalDepCommand: "go run /workspaces/butler/user_commands/go_external_deps_method.go"
    TaskCommands: 
      LintCommand: "echo go lint command"
      TestCommand: "echo go test command"
      BuildCommand: "echo go build command"
      PublishCommand: "echo go publish command"
      SetUpCommands:
          - "echo go test"